service: bellapp
frameworkVersion: '2'
useDotenv: true

provider:
  name: aws
  runtime: nodejs14.x
  lambdaHashingVersion: 20201221
  environment:
    LINE_ACCESS_TOKEN: ${env:LINE_ACCESS_TOKEN}
    TARGET_USER_ID: ${env:TARGET_USER_ID}


functions:
  ring:
    handler: handler.ring
    events:
      - httpApi:
          path: /bell/ring
          method: get
